#+title: Simple CRUD | TypesCript + React + PostgreSQL

Este projeto é um CRUD (Create Read Update Delete) feito como desafio para um processo de seleção de um estágio.
A proposta era utilizar [[https://react.dev/][React]] e [[https://nodejs.org/en][NodeJS]] para desenvolver a aplicação, fazendo telas para Registro de produtos,
modificação de produtos, apresentação de produtos, e haviam 3 desafios, criar um widget de paginação do 0, e
criar mais duas telas, uma que apresenta os 3 produtos mais caros, e outra com os 3 produtos com maior estoque.
Foi especificada a estrutura de um produto dentre outras coisas.

Fiz o projeto com todos os desafios, o maior sendo o widget de paginação. Acabei sendo selecionado mas o recrutador
nunca mais entrou em contato.. (então será que fui selecionado mesmo?!). Escolhi depois de uns meses adaptar o projeto
para [[https://www.typescriptlang.org/][TypeScript]] e integrá-lo com [[https://www.postgresql.org/][PostgreSQL]] (antes o projeto tinha um array em memória com os produtos por questão de
simplicidade). Desde o principio *StyledComponents* foi utilizado para adcionar estilo aos elementos.

A aplicação foi hospedada utilizando o serviço de hospedagem do [[https://render.com/][Render]], tanto o servidor quanto o banco de dados.
Eis o link para acessálo: https://simples-crud-challenge.onrender.com

* Estrutura do código fonte
+ Pasta raiz/
  - [[https://github.com/odecam0/desafio-thummi/blob/main/index.ts][index.ts]] -> Código fonte do servidor, utilizando [[https://expressjs.com/][Express.js]], e queries para o [[https://www.postgresql.org/][PostgreSQL]] utilizando o pacote [[https://github.com/porsager/postgres][Postgres]]
  - [[https://github.com/odecam0/desafio-thummi/blob/main/db.mjs][db.mjs]]   -> Modulo que conecta no banco de dados e exporta um objeto para acessá-lo
  + client/  
    + src/   -> Pasta com o código fonte do Front-End utilizando [[https://react.dev/][React]]
      - [[file:client/src/App.js][App.js]] -> Arquivo com componente da barra de navegação utilizando *react-router-dom*.
      - [[file:client/src/RegisterProduct.tsx][RegisterProduct.tsx]] -> Componente com formulário para registro de um produto
      - [[file:client/src/ModifyProduct.tsx][ModifyProduct.tsx]] -> Componente com formulário para modificação de um produto
      - [[file:client/src/ShowProducts.tsx][ShowProducts.tsx]] -> Componente que exibe produtos cadastrados, utiliza componente de paginação que foi desenvolvido
      - [[file:client/src/PaginationWidget.tsx][PaginationWidget.tsx]] -> Componente de paginação genérico
      - [[file:client/src/ExpensiveProducts.tsx][ExpensiveProducts.tsx]] -> Componente que exibe apenas 3 produtos, os mais caros
      - [[file:client/src/MostInStock.tsx][MostInStock.tsx]] -> Componente que exibe os 3 produtos com maior estoque
      - [[file:client/src/CustomTypes.ts][CustomTypes.ts]] -> Arquivo que defino o tipo Product que utilizado em muitos arquivos
      - [[file:client/src/StyledButton.js][StyledButton.js]] -> Arquivo com o CSS para os botões no projeto
      - [[file:client/src/StyledForm.js][StyledForm.js]] -> Arquivo com o CSS para os formulários
      - [[file:client/src/TableStyle.js][TableStyle.js]] -> Arquivo com o CSS para as tabelas

* Paginação

No código fonte do componente de paginação, há um [[file:client/src/PaginationWidget.tsx::// Existem 3 casos que podem ocorrer][grande comentário]] explicando a lógica por trás do
funcionamento do componente. Em primeiro lugar, o componente recebe 4 propriedades importantes.

[[file:client/src/PaginationWidget.tsx::interface PaginationProps {][Techo do código]]
#+begin_src typescript
interface PaginationProps {
    max_p: number; // Esta propriedade representa o número máximo de páginas que deve
                   // aparecer na barra de paginação.
    total_p: number; // Esta propriedade representa o total de páginas que existem
    this_p: number; // Esta propriedade representa a página atual
    goto_page: (n:number) => void; // Esta função será explicada à parte
    className: string; // Este atributo serve para o StyledComponents apenas
}
#+end_src



* Coisas a fazer:
- [ ] Escrever uma breve descrição para cada arquivo na pasta client/src/.
- [ ] Documentar como a paginação está sendo feita.
- [ ] Adcionar type annotations nas requisições e respostas em index.ts.
